CREATE DATABASE DU1
GO
USE DU1

CREATE TABLE MauSac(

    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Ma VARCHAR(30) UNIQUE,
    Ten VARCHAR(50)

)

CREATE TABLE Imei(

    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Ma VARCHAR(30) UNIQUE,
    SoImei BIGINT

)

CREATE TABLE SanPham(

    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Ma VARCHAR(30) UNIQUE,
    Ten VARCHAR(50),

)

CREATE TABLE Chipse(

    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Ma VARCHAR(30) UNIQUE, 
    Ten VARCHAR(50)

)

CREATE TABLE Pin(

    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Ma VARCHAR(30) UNIQUE,
    Ten VARCHAR(50)

)

CREATE TABLE PhanLoaiHang(

    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Ma VARCHAR(30) UNIQUE,
    Ten VARCHAR(50)

)

CREATE TABLE Ram(

    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Ma VARCHAR(30) UNIQUE,
    Ten VARCHAR(50)

)

CREATE TABLE Rom(

    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Ma VARCHAR(30) UNIQUE,
    Ten VARCHAR(50)

)

CREATE TABLE ManHinh(

    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Ma VARCHAR(30) UNIQUE,
    Ten VARCHAR(50)

)

CREATE TABLE Camera(

    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Ma VARCHAR(30) UNIQUE,
    Ten VARCHAR(50)

)

CREATE TABLE XuatXu(

    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Ma VARCHAR(30) UNIQUE,
    Ten VARCHAR(50)

)

CREATE TABLE DongSP(

    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Ma VARCHAR(30) UNIQUE,
    Ten VARCHAR(50)
)

CREATE TABLE ChiTietSP(

    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    IdSP UNIQUEIDENTIFIER FOREIGN KEY(IdSP) REFERENCES SanPham(id),
    IdImei UNIQUEIDENTIFIER FOREIGN KEY(IdImei) REFERENCES Imei(id),
    IdMauSac UNIQUEIDENTIFIER FOREIGN KEY(IdMauSac) REFERENCES MauSac(id),
    IdChipse UNIQUEIDENTIFIER FOREIGN KEY(IdChipse) REFERENCES Chipse(id),
    IdPin UNIQUEIDENTIFIER FOREIGN KEY(IdPin) REFERENCES Pin(id),
    IdPhanLoaiHang UNIQUEIDENTIFIER FOREIGN KEY(IdPhanLoaiHang) REFERENCES PhanLoaiHang(id),
    IdRam UNIQUEIDENTIFIER FOREIGN KEY(IdRam) REFERENCES Ram(id),
    IdRom UNIQUEIDENTIFIER FOREIGN KEY(IdRom) REFERENCES Rom(id),
    IdManHinh UNIQUEIDENTIFIER FOREIGN KEY(IdManHinh) REFERENCES ManHinh(id),
    IdCamera UNIQUEIDENTIFIER FOREIGN KEY(IdCamera) REFERENCES Camera(id),
    IdXuatXu UNIQUEIDENTIFIER FOREIGN KEY(IdXuatXu) REFERENCES XuatXu(id),
    IdDongSP UNIQUEIDENTIFIER FOREIGN KEY(IdDongSP) REFERENCES DongSP(id),
    GiaNhap DECIMAL(20,0) DEFAULT 0,
    GiaBan DECIMAL(20,0) DEFAULT 0,
    NamBH INT,
    MoTa VARCHAR(100),
    SoLuongTon INT,
    TrangThai INT

)

CREATE TABLE ChucVu(

    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Ma VARCHAR(30),
    Ten VARCHAR(50)

)

CREATE TABLE NhanVien(

    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Ma VARCHAR(30) UNIQUE,
    Ten VARCHAR(100),
    NgaySinh DATE,
    DiaChi VARCHAR(255),
    Sdt VARCHAR(30),
    Email VARCHAR(100),
    MatKhau VARCHAR(50),
    NgayTao DATE,
    GhiChu VARCHAR(100),
    TrangThai INT,
    IdChucVu UNIQUEIDENTIFIER FOREIGN KEY(IdChucVu) REFERENCES ChucVu(id)

)

CREATE TABLE KhachHang(

    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Ma VARCHAR(30),
    Ten VARCHAR(100),
    Sdt VARCHAR(30),
    NgaySinh DATE,
    DiaChi VARCHAR(255),
    GioiTinh INT,
    TrangThai INT,
    GhiChu VARCHAR(100),
    SoLanMua INT

)

CREATE TABLE GiamGia(

    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Ma VARCHAR(30),
    TenCT VARCHAR(100),
    NgayTao DATE,
    NgayDienRa DATE,
    NgayKetThuc DATE,
    SoTienGiam DECIMAL(20,0) DEFAULT 0

)

CREATE TABLE HoaDon(

    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    IdNhanVien UNIQUEIDENTIFIER FOREIGN KEY(IdNhanVien) REFERENCES NhanVien(id),
    IdKH UNIQUEIDENTIFIER FOREIGN KEY(IdKH) REFERENCES KhachHang(id),
    IdGiamGia UNIQUEIDENTIFIER FOREIGN KEY(IdGiamGia) REFERENCES GiamGia(id),
    Ma VARCHAR(30),
    NgayTao DATE,
    NgayThanhToan DATE,
    NgayShip DATE,
    TienShip DECIMAL(20,0) DEFAULT 0,
    TienCoc DECIMAL(20,0) DEFAULT 0,
    NgayNhan DECIMAL(20,0) DEFAULT 0,
    TenKh VARCHAR(50),
    SdtNguoiNhan VARCHAR(30),
    SdtNguoiShip VARCHAR(30),
    TenNguoiShip VARCHAR(50),
    MaVanChuyen VARCHAR(30),
    TinhTrang int,
    SoTienGiam DECIMAL(20,0) DEFAULT 0

)

CREATE TABLE HoaDonChiTiet(

    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    IdChiTietSP UNIQUEIDENTIFIER FOREIGN KEY(IdChiTietSP) REFERENCES ChiTietSP(id),
    IdHoaDon UNIQUEIDENTIFIER FOREIGN KEY(IdHoaDon) REFERENCES Hoadon(id),
    SoLuong INT,
    DonGia DECIMAL(20, 0) DEFAULT 0,
    TrangThai int

)

CREATE TABLE ImeiDaBan(

    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MaImei VARCHAR(30) UNIQUE,
    TrangThai INT,
    idHoaDonCT UNIQUEIDENTIFIER FOREIGN KEY(idHoaDonCT) REFERENCES HoaDonChiTiet(id)

)

